Enable GTS DA
NOAA-PSL/land-offline_workflow pull request #35
Opened 2024-11-15 18:19 UTC by yuanxue2870

## Describe your changes  
Summarise all code changes included in PR: 
All edits are made in the DA_update submodule, which include:
1.Fix bugs for $WINLEN
2.Correct typos in the do_landDA.sh
3.Add Jiarui's current GTS yaml and add the elevation check (to be consistent with GHCN.yaml filters)
4.Enable 6-hr cycle for GTS DA

List any associated PRs in the submodules.
https://github.com/NOAA-PSL/land-DA_update/pull/25

## Issue ticket number and link
List the git Issue that this PR addresses: 

## Test output 
Is this PR expected to pass the DA_IMS_test (ie., does it change the output)? 
Yes
Does it pass the DA_IMS_test? 
Yes
If changes to the test results are expected, what are these changes? Provide a link to the output directory when running the test: 
N/A
## Checklist before requesting a review
- [x] My branch being merged is up to date with the latest develop. 
- [x] I have performed a self-review of my code by examining the differences that will be merged.
- [x] I have not made any unnecessary code changes / changed any default behavior.
- [x] My code passes the DA_IMS_test, or differences can be explained.

2024-11-18 15:33 UTC, yuanxue2870 commented
Please review: @ClaraDraper-NOAA @jiaruidong2017, Thank you!

2025-04-07 22:13 UTC, ClaraDraper-NOAA commented
@yuanxue2870 Is this PR still relevant?

2025-04-08 13:56 UTC, yuanxue2870 commented
> @yuanxue2870 Is this PR still relevant?

Still relevant. The PR is supposed to have the final version of GTS reject list plus SOGR feature. I have now converted it to draft for now as I think some of Jiarui's PRs were just merged last night, which makes this old PR has conflicts. I will need some time to make edits and let you know when to review. Thanks!

2025-04-08 16:45 UTC, ClaraDraper-NOAA requested changes

2025-04-08 16:45 UTC, ClaraDraper-NOAA commented on .gitmodules
> +        branch =feature/GTSDA
The only change in this PR is to point to your branch of land-DA_update. The submodules should not be changed here in this file. Instead delete this PR, and submit a PR to the land-DA_update submodule, since that's where your changes are.

2025-04-08 16:53 UTC, yuanxue2870 commented on .gitmodules
> +        branch =feature/GTSDA
OK. Will do.

2025-04-08 16:53 UTC, closed without merging

2025-04-08 17:15 UTC, ClaraDraper-NOAA commented
The majority of the edits required for GTS DA were embedded in Jiarui's PRs in https://github.com/NOAA-PSL/land-DA_update/pull/31 [merged] and https://github.com/NOAA-PSL/land-DA_update/pull/33 [not merged]. Hence, I do not need to submit another GTS DA PR for neither offline workflow nor land-DA_update because the latest DA_update hash (bb45343) is now consistent with the /develop (head) (these two are being inconsistent for quite a while, which confused me and Jiarui as we sit down and discussed a bit, thanks again for your clarification this morning!). So, in all, once both Jiarui's PRs are merged, the GTS DA capability will be enabled in the offline workflow.