Add capability to run the JEDI LETKF DA in offline land DA workflow
NOAA-PSL/land-offline_workflow pull request #37
Opened 2024-11-21 12:04 UTC by tsga

## Describe your changes  
Adds capability to run LETKF DA (full ensembles) in the land offline workflow. The codes for the other DA methods 2DVar and LETKF-OI remain the same (and old tests works as they are). The changes from these PRs are preparing input files for JEDI letkf (and vector to tile, add jedi increment) executables in ensemble form.

## Related PRs

- A companion PR for the land-DA_update submodule (https://github.com/NOAA-PSL/land-DA_update/pull/27) 

-  The merged PR https://github.com/NOAA-PSL/land-apply_jedi_incr/pull/6 to land-DA_update's submodule "land-apply_jedi_incr" 

- A submodule for generating ensemble forcing using the Stochastic Physics module is added here (https://github.com/tsga/stochastic_physics/tree/lnd_ens)

## Test output 
This PR doesn't change the current tests and it passes the 2DVar (GHCN + IMS) test

Additional test set for LETKF with 20 ensemble members prepared.

## Checklist before requesting a review
- [ ] My branch being merged is up to date with the latest develop. 
- [ ] I have performed a self-review of my code by examining the differences that will be merged.
- [ ] I have not made any unnecessary code changes / changed any default behavior.
- [ ] My code passes the DA_IMS_test, or differences can be explained.

2024-12-20 19:23 UTC, ClaraDraper-NOAA requested changes
Can you please remove all the directory values that are pointing to your directories? 

For output directories, we can set a default using $USER. For input directories, any necessary data should be in either my DA_test_cases or on the LAND directory.

2024-12-20 19:23 UTC, ClaraDraper-NOAA commented on .gitmodules
> +	url = https://github.com/tsga/stochastic_physics
Later, we should switch to using the UFS repo here (and merge any necessary changes in there).

2024-12-20 19:23 UTC, ClaraDraper-NOAA commented on STOCHY/RESTART/stochy_final_ens9.nc
Are these needed? Or can the user generate them themselves? 

If they are needed, since we're only on hera, it'd be better to stage these somewhere than include them in the repo. I suggest creating a directory within the LAND directory, copying them across and then setting it to read only.

2024-12-20 19:23 UTC, ClaraDraper-NOAA commented on check_test.sh
> +#TEST_BASEDIR=${ICSDIR}/mem000/restarts/vector/
delete comment.

2024-12-20 19:23 UTC, ClaraDraper-NOAA commented on ens_da/generate_ens_forc.nml
> +  forc_inp_path = "/scratch1/NCEPDEV/da/Tseganeh.Gichamo/land-offline_workflow/"
Can we set a better default? Is this directory different from Mike's in any way?

2024-12-20 19:23 UTC, ClaraDraper-NOAA commented on ens_da/submit_cycle_letkf.sh
> +export gdasapp_mods=/scratch1/NCEPDEV/da/Tseganeh.Gichamo/GDASApp/modulefiles
this needs to changed. I link GDASApp in the LAND directory into the DAupdate directory. If you need a newer GDASApp, you can update the one on the LAND directory.

2024-12-20 19:23 UTC, ClaraDraper-NOAA commented on ens_da/submit_cycle_letkf.sh
> +export ufs_mods=/scratch1/NCEPDEV/da/Tseganeh.Gichamo/global-workflow/sorc/ufs_model.fd/modulefiles
More directories that need to be changed. All directories should be shared ones (either my land_DA_tests, or on LAND).

2024-12-20 19:23 UTC, ClaraDraper-NOAA commented on ens_da/submit_cycle_letkf.sh
> +export BUILD_DIR=/scratch1/NCEPDEV/da/Tseganeh.Gichamo/GDASApp/build/
directory.

2024-12-20 19:23 UTC, ClaraDraper-NOAA commented on ens_da/submit_cycle_letkf.sh
> +module purge
Better to put the model info in a separate file and source it.

2024-12-20 19:36 UTC, tsga commented on ens_da/generate_ens_forc.nml
> +  forc_inp_path = "/scratch1/NCEPDEV/da/Tseganeh.Gichamo/land-offline_workflow/"
The file should not exist in the first place. Deleted.

2024-12-20 19:40 UTC, tsga commented on STOCHY/RESTART/stochy_final_ens9.nc
They are not strictly needed, unless someone wants to start from initial conditions. I will delete them then add in the document where to find them if anyone wants to use initial files.

2024-12-20 19:56 UTC, tsga commented on .gitmodules
> +	url = https://github.com/tsga/stochastic_physics
Will do. I have taken note.

2024-12-20 19:56 UTC, ClaraDraper-NOAA commented on STOCHY/RESTART/stochy_final_ens9.nc
I like this solution.

2025-01-05 18:14 UTC, tsga commented
> Can you please remove all the directory values that are pointing to your directories?
> 
> For output directories, we can set a default using $USER. For input directories, any necessary data should be in either my DA_test_cases or on the LAND director

Resolved

2025-11-22 16:02 UTC, closed without merging